### ISSUE TITLE
Shapes by stylet are not precisely recognized 

### ISSUE THREAD

**Issue by Iey4iej3** [saber-notes/saber#1005]
### Describe the bug

Shapes are not correctly recognized when drawn by SPen. They could however be correctly recognized when drawn by finger.

### To reproduce

1. Choose the shape tool;
2. Draw a rectangle clockwise by SPen.

### Expected behavior

The rectangle is recognized and automatically vectorized.

(Current behavior: it is recognized as a line, and a line segment from the initial point to the final point is drawn after releasing the stylet)

### Saber version

v0.17.1 F-Droid (17010)

### Device

- Device: Samsung S6 Lite
- OS: LineageOS 20 (Android 13)

**Comment by ZebraVogel94349** [comment]
When drawing by finger, the shapes also often don't get recognized correctly. Many strokes that should get recognized as a line get recognized as a circle instead or not at all.

**Comment by ZebraVogel94349** [comment]
> > When drawing by finger, the shapes also often don't get recognized correctly. Many strokes that should get recognized as a line get recognized as a circle instead or not at all.
> 
> Strange that I experienced the exact opposite. Anyways, now another algorithm is used now, and I will test it when an F-Droid build is available. (There is a current round of building, thus it will appear soon.)

I tested it using the latest version. I don't know how it was before version 1.18.2 when drawing by finger.

**Comment by Iey4iej3** [comment]
Latest Saber uses a different algorithm and the behavior is completely different, thus close this issue.
