### ISSUE TITLE
Tapping with stylus button pressed causes undo

### ISSUE THREAD

**Issue by atahanacar** [saber-notes/saber#1006]
### Describe the bug

When using the stylus on my Samsung Tab S6 Lite, any time I tap on the screen with the button pressed and the undo action happens, the next stroke with the stylus is the eraser instead of the pen.

### To reproduce

1. Tap with the stylus while holding down the button.
2. Observe the undo action.
3. Release the button.
4. Try to write something
5. Observe the eraser getting activated

### Expected behavior

The selected tool (pen) should have been used instead of the eraser.

### Saber version

v0.17.1 F-Droid (17010)

### Device

- Device: Samsung Galaxy Tab S6 Lite
- OS: Android 13 (LineageOS)

**Comment by fritzrehde** [comment]
Observing the same thing on exactly the same device and OS.

**Comment by wold9168** [comment]
Same bug on my device(Samsung Galaxy Tab S8)
One UI Version: 5.1.1
Android Version:13
