### ISSUE TITLE
Width of shape tool becomes 10 every time the app restarts

### ISSUE THREAD

**Issue by Iey4iej3** [saber-notes/saber#1007]
### Describe the bug

The width of stroke of shape tool becomes 10 every time the app restarts (e.g. removed from the drawer of recent apps, or killed).

### To reproduce

1. Set the width of stroke of shape tool to be, say, 2.
2. Kill the app.
3. Restart the app.

### Expected behavior

The width of stroke should be the same as the value before the restart.

### Saber version

v0.17.1 F-Droid (17010)

### Device

- Device: -
- OS: Android 13

**Comment by ceskyDJ** [comment]
I have the same problem.
