### ISSUE TITLE
Line detection

### ISSUE THREAD

**Issue by Iey4iej3** [saber-notes/saber#1019]
### Motivation

This functionality was removed when the shape tool was introduced. However, there are several advantages of line detection over the shape tool:

1. As mentioned in https://github.com/saber-notes/saber/discussions/970#discussion-5771538 the lines were perfectly horizontal or vertical, while the current shape tool does not produce such perfect lines.
2. The shape tool has a much heavier computational overhead. The lag is obvious with stylus, and it is quite intolerable on, say, Onyx Boox.

### Solution

Bring back the line detection functionality.

### Saber version

v0.17.2 F-Droid (17020)

### Device

- Device: -
- OS: -

**Comment by adil192** [comment]
I'm working on a faster shape recognition package, see [one_dollar_unistroke_recognizer](https://pub.dev/packages/one_dollar_unistroke_recognizer).
I'll add back line snapping when it's ready, as well as line recognition without needing to use the shape pen.

**Comment by adil192** [comment]
@Iey4iej3 How is the lag now with v0.18.3?

**Comment by Iey4iej3** [comment]
I will test it on my Onyx Boox when it is available on F-Droid. However, I still think that the previous line detection is of use (although it seems easier than before to produce perfect horizontal or vertical lines via the shape pen, as I tested on my laptop in the flatpak version). It can be done without switching the mode, which seems useful when I am taking notes.

**Comment by Iey4iej3** [comment]
The line detection is back in v0.21.3.
