### ISSUE TITLE
PDF exports not working

### ISSUE THREAD

**Issue by RamsaKd** [saber-notes/saber#1026]
### Describe the bug

When I try to export a note as a pdf it just spins endlessly and never actually exports.

### To reproduce

1. Make a note
2. Try to export it as a pdf

### Expected behavior

It should take some time and then export

### Saber version

0.18.3 Foss android

### Device

- Device: Google Pixel 7 Pro
- OS: Android 14

**Comment by adil192** [comment]
I can't reproduce this, please can you tell me what features are in your note like pdfs, images, shapes, etc?

**Comment by fritzrehde** [comment]
I also experience this. I'm on the Samsung Tab S6 Lite running LineageOS 20 (Android 13). When I click on the export as PDF button, the app freezes and eventually crashes. The note in question is a long PDF (around 80 pages) where I annotated the first page with my S Pen.

**Comment by fritzrehde** [comment]
Maybe this is related to #919?

**Comment by hankertrix** [comment]
Similar problem on iPad: #740

**Comment by RamsaKd** [comment]
> I can't reproduce this, please can you tell me what features are in your note like pdfs, images, shapes, etc?

I've encountered this issue with pdfs with nothing but handwriting on them as well as ones with handwriting, pdfs & images in any possible combination of those 3. But I have also been able to export pdfs with handwriting on them. I have had this issue on linux, grapheneOS & on a samsung galaxy tab s7 fe.

**Comment by RamsaKd** [comment]
I've attached a zip with 2 files, one that successfully exports & one that doesn't. Both are nothing more than handwriting. They were part of 1 multi-page file that I deleted parts of for each version if that is relevant.
[Uploading Export.zip…]()

**Comment by RamsaKd** [comment]
I've attached a zip with 2 files, one that successfully exports & one that doesn't. Both are nothing more than handwriting. They were part of 1 multi-page file that I deleted parts of for each version if that is relevant.
[Uploading Export.zip…]

**Comment by RamsaKd** [comment]
I've attached a zip with 2 files, one that successfully exports & one that doesn't. Both are nothing more than handwriting. They were part of 1 multi-page file that I deleted parts of for each version if that is relevant. [https://drive.proton.me/urls/0JG7TVCF68#QJyFrAUWHiDB](url)

**Comment by BHuck74** [comment]
Hi there!

I've also attached a zip with one document that successfully exports, and the other doesn't. For the one that doesn't export, I've included the .sba file (export to .sba works, only pdf does not).

[Archive.zip](https://github.com/saber-notes/saber/files/14276506/Archive.zip)

**Comment by arpandaze** [comment]
> I've attached a zip with 2 files, one that successfully exports & one that doesn't. Both are nothing more than handwriting. They were part of 1 multi-page file that I deleted parts of for each version if that is relevant. [https://drive.proton.me/urls/0JG7TVCF68#QJyFrAUWHiDB](url)



> Hi there!
> 
> I've also attached a zip with one document that successfully exports, and the other doesn't. For the one that doesn't export, I've included the .sba file (export to .sba works, only pdf does not).
> 
> [Archive.zip](https://github.com/saber-notes/saber/files/14276506/Archive.zip)

I have tested and can confirm both of your files export fine with this: https://github.com/saber-notes/saber/pull/1135
