### ISSUE TITLE
Shape tool: incorrectly recognized as a circle

### ISSUE THREAD

**Issue by Iey4iej3** [saber-notes/saber#1039]
### Describe the bug

It happens that the new algorithm of the shape tool often incorrectly recoginizes circles.

### To reproduce

1. Switch to shape tool;
2. draw some horizontal lines, say

### Expected behavior

When a shape is more similar to a line, it should be recognized as a line instead of a circle.

### Saber version

v0.18.3

### Device

- Device: -
- OS: -

### Anything else?

https://github.com/saber-notes/saber/assets/1880768/6a976b69-27fa-41ca-8d49-1a77aea755a8

**Comment by Crowerade** [comment]
I agree, I think the algorithm (although way better than it was before) still needs some improvements, it almost every time struggle to recognise a square when the horizontal lines are greater than the vertical ones.
