### ISSUE TITLE
Add a Recycle Bin

### ISSUE THREAD

**Issue by Groonir** [saber-notes/saber#1040]
### Motivation

deleted my notes by accident quite a few times

### Solution

add a Recycle Bin where deleted files are stored for a month before deletion

### Alternatives

add secondary confirmation to deletion button
or place deletion Button further away from share button

### Saber version

v0.18.3 F-Droid

### Device

- Device: Samsung Tab 9
- OS: android 13

**Comment by Iey4iej3** [comment]
Duplicate of https://github.com/saber-notes/saber/issues/399
