### ISSUE TITLE
Better language signpost in `README.md`

### ISSUE THREAD

**Issue by ceskyDJ** [saber-notes/saber#1084]
Currently we have a signpost for various languages of "README" in `README.md`, that looks like this:
![image](https://github.com/saber-notes/saber/assets/48548230/c78aa281-68ad-4af3-98eb-e5395d82b594)

It has some problems in languages like Czech, when there is more complex rules for size of the first letter of language name (Čeština vs čeština), because there isn't always big letter like in other languages (like e.g. English and German). The second problem is word inflection. The sentence "You can read this file in" requires the language name to be in a special form, so it's not consistent and I'm sure it's not too clear for understand.

I propose changing our signpost to simpler form used by tuyafeng/Via:
![image](https://github.com/saber-notes/saber/assets/48548230/a83c7287-8a7a-4b0b-bfa1-86ee13a23f55)

Here are just language names divided by a pipe. Language names could be in a base form and with big first letter. It's simple and well understandable, at least I think. Of course, logo position isn't subject of this discussion, Saber has just perfect position of it. What do you mean?

**Comment by AkintolaRichard** [comment]
@ceskyDJ this is awesome and I would love to join in implementing this.
@adil192 please can you can provide guidance implementing this?

**Comment by ernest-emmanuel-utibe** [comment]
@ceskyDJ great job
@adil192 Like @AkintolaRichard has said, please provide enough guidance for implementing this.

To me, the proposed solution suggests simplifying the format to just language names divided by a pipe, using a base form of the language name with an initial capital letter.

Instead of using full-language names, consider utilizing standardized language codes like ISO 639-1 codes (two-letter codes) or ISO 639-3 codes (three-letter codes). This could provide a more concise and universally recognized way to represent languages.

If space allows or in a dynamic setting (like a web interface), consider implementing a tooltip or hover feature that displays the full language name when users hover over or click on the language code or name. This can provide additional clarity without cluttering the primary signpost

This simpler format aims to avoid issues related to complex capitalization rules and word inflection that might occur in certain languages.

**Comment by ceskyDJ** [comment]
Hi @AkintolaRichard and @ernest-emmanuel-utibe! I don't completely understand, what do you want from me. So, could you be more specific, please?

I try to help @adil192 with spreading Saber's localization support. I tried to translate README some time ago and it also tried to convince other contributors to translate README to their native languages, too. It ended with README translated to a few (I think 3 without the original English version) languages. The problem I see there is with the language signpost. It's hard to understand and has problems with letter capitalization, as I've written before. So, I try to enhance it to a very simple but useful form.

Language names displayed there should be self-explanatory, shouldn't they? If there is some problem with understanding, feel free to let us know, so we can offer a better solution. I don't get the idea around the hover effect and these things. Could you provide more information about it, please?

If you want to translate Saber, there is a guide for it in README. I don't know what language is used in Nigeria, you're both from (at least you have so in your GitHub profiles). Google just says something about English and many other languages.

**Comment by adil192** [comment]
@ceskyDJ Yes I'm happy making this change. I didn't expect the sentence to alter the language names originally!

**Comment by adil192** [comment]
@ceskyDJ Please can you confirm if "Čeština" is the correct form?

**Comment by ceskyDJ** [comment]
> @ceskyDJ Please can you confirm if "Čeština" is the correct form?

Yes, it's correct.

**Comment by ceskyDJ** [comment]
> @ceskyDJ Yes I'm happy making this change. I didn't expect the sentence to alter the language names originally!

Thanks for your support. I think it will be way better.

**Comment by adil192** [comment]
> > @ceskyDJ Please can you confirm if "Čeština" is the correct form?
> 
> Yes, it's correct.

![image](https://github.com/saber-notes/saber/assets/21128619/27daf9d3-785f-457b-abc9-6e4eb705b668)

Would you like the in-app language name to also be `Čeština` or to remain as `čeština`?

**Comment by ceskyDJ** [comment]
> > > @ceskyDJ Please can you confirm if "Čeština" is the correct form?
> > 
> > Yes, it's correct.
> 
> <img src="https://github.com/saber-notes/saber/assets/21128619/27daf9d3-785f-457b-abc9-6e4eb705b668" alt="The Saber language selector with the lowercase form of čeština" width=400>
> 
> Would you like the in-app language name to also be `Čeština` or to remain as `čeština`?

Oh, you got me! It's nonsense to have „Čeština“ in README, because it's a general word in Czech, so with a small first letter. Could you please use the small one in the README? I'm sorry for the misinformation.

**Comment by ceskyDJ** [comment]
There is one more thing. I think about this button inside of Saber:
![Screenshot_20240110_140553.jpg](https://github.com/saber-notes/saber/assets/48548230/693f0068-51df-4af4-ad5d-eb17dbccb08f)

Maybe it will be better to link the translated PRICING file for supported languages (or at least link PRICING.md with signpost for every language but English for simplicity). Now, it links GitHub sponsors, which is just in English, so users could be confused and translated PRICING won't be much effective (I think most users don't go straight to the repository). What do you think?

**Comment by adil192** [comment]
![image](https://github.com/saber-notes/saber/assets/21128619/ca242807-340c-4e49-ae33-84bd7ccf222b)

**Comment by ceskyDJ** [comment]
> ![image](https://private-user-images.githubusercontent.com/21128619/297458241-ca242807-340c-4e49-ae33-84bd7ccf222b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTQ5ODMsIm5iZiI6MTcwNTUxNDY4MywicGF0aCI6Ii8yMTEyODYxOS8yOTc0NTgyNDEtY2EyNDI4MDctMzQwYy00ZTQ5LWFlMzMtODRiZDdjY2YyMjJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE4MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMzM3YWNkNjQ1MzVhMTY1MzlkODBmM2RmZGJmYjRlNjEwOGRkODkzZDNhM2FmOWU0MDVmYjE0MGE5ODMwZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RXRmbch4s4u85YI7fj9kAcdGwd0j4XlRXYapF78q20Q)

I don't know this is the best solution. There is still an English (and pretty complicated for people that don't know English or know just poor basics) sentence you need to understand. Anyway, it's better than nothing.
