### ISSUE TITLE
An option for infinite canvas note-taking?

### ISSUE THREAD

**Issue by GurrenLagann114** [saber-notes/saber#1089]
### Motivation

An infinite canvas mode would be nice to write mental maps and making schemes.

### Solution

The closest inspiration I'm thinking about would be OneNote, with a very large board that's basically infinite.

### Saber version

v0.19.0 (19000)

### Device

- Device: Tab S8+
- OS: Android 14

**Comment by ZebraVogel94349** [comment]
This is a duplicate of #88 .

**Comment by GurrenLagann114** [comment]
Ok, rather than pointing out useless details (because I was certainly not going to look through 1000 issues) could I know if it is at least possible, since no answer was provided here nor on #88?

**Comment by adil192** [comment]
Yes it's technically feasible. No I'm not implementing it right now. Closing as duplicate of #88.

**Comment by GurrenLagann114** [comment]
> Yes it's technically feasible.

👍
