### ISSUE TITLE
New versions not available on F-Droid

### ISSUE THREAD

**Issue by Crowerade** [saber-notes/saber#1113]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

The new versions of the app are not available on F-Droid. The current version for F-Droid is v0.19.0

### To reproduce

1. Search Saber on F-Droid
2. Look up the current version
3. It is v0.19.0

### Expected behavior

Then new versions should appear on F-Droid.

### Saber version

v0.19.0 F-Droid

### Device

- Device: Samsung Galaxy Tab S6 Lite
- OS: One UI

**Comment by QubaB** [comment]
See  issue  #1103

**Comment by Crowerade** [comment]
> See issue #1103

Oh thanks, I didn't see that !
