### ISSUE TITLE
Can't export to pdf

### ISSUE THREAD

**Issue by ThmsDhn** [saber-notes/saber#1125]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

Hello

I'm using your great app with a Nextcloud server: 
- on my linux laptop (version v.0.19.2 (19020)); 
- on a Lenovo Tab P12 and on my smartphone (version v.0.19.2 F-Droid (19020)).

On each device, i have the same problem : i manage to export my projects to sba format but i can't export as pdf. The wheel is going around but nothing happens...

Could you please help me ?

### To reproduce

Export project as pdf.

### Expected behavior

Export as pdf to my Nextcloud server.

### Saber version

v.0.19.2 (19020)

### Device

Laptop :  Linux Mint LMDE 6

Tablet : Lenovo Tab P12

**Comment by QubaB** [comment]
Did you tried to update to 0.19.4? There is fix of export on iOS, may be it helps.

I think that export is done only to device. Not to Nextcloud.

**Comment by ThmsDhn** [comment]
Hello 
Thanks for the help !
Yes, i'm already with 0.19.4 on each device.
A friend had the same problem on iOS and 0.19.4 effectively fixed it.
Two or three months ago, i was able to export as pdf directly to my Nextcloud (or to device, or to email...).

**Comment by saihaze** [comment]
Same problem, 0.20.1 on Android.

**Comment by iniyanijoseph** [comment]
Same issue, it doesn't work for 20.1 on Android, on a Macbook, or on Linux (Debian Appimage).

**Comment by arpandaze** [comment]
Can you guys please confirm whether this fixes for you or not: https://github.com/saber-notes/saber/pull/1135 ?

**Comment by iniyanijoseph** [comment]
> Can you guys please confirm whether this fixes for you or not: #1135 ?

That was it for me. Hopefully this gets merged soon.

**Comment by QubaB** [comment]
I tested two files of @ThmsDhn (Weierstrass and Riemann) and pdf was exported correctly. 

I think that @arpandaze fix works well.
