### ISSUE TITLE
App does not sync with clouds that have 2FA.

### ISSUE THREAD

**Issue by GuiSousa135** [saber-notes/saber#1127]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

App notes do not sync with cloud services that have second factor authentication (2FA OTP), this applies to both default server and the custom servers.

### To reproduce

1. Enable the second authentication factor on your Nextcloud account.

3. Log in with the Saber app (using only the default fields).

4. Look at the error message.

### Expected behavior

If the cloud (whether the standard server or a custom server) that the user wanted to synchronize the notes with has some type of second authentication enabled, the application cannot access the service with just the password. The ideal would be to have another numeric field in the login area to add the second authentication factor, this way the application would be able to log in to Nextcloud clouds.

### Saber version

V 0.19.3 F-Droid.

### Device

- Device: Samsung Tab S6 Lite
- OS: Android 12L

- Device: Samsung Galaxy S20 FE
- OS: Android 12

- Device: Google Pixel 6
- OS: Android 13

### Anything else?

Tested on multiple devices with the latest versions of the Saber app, both with the default server and custom Nextcloud servers.

**Comment by ceskyDJ** [comment]
I completely agree with @QubaB. I have a Nextcloud instance with 2FA and logging in into Saber using app password works just fine.

**Comment by ceskyDJ** [comment]
I agree. Saber (like other apps working with Nextcloud) shouldn't use account passwords for logging in into Nextcloud at all. It should retrieve app passwords instead. @adil192, could you look at it, please? Here is a Nextcloud documentation page about this problem: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html.

**Comment by adil192** [comment]
Closed with https://github.com/saber-notes/saber/pull/1246
