### ISSUE TITLE
Text Feature ist unusable

### ISSUE THREAD

**Issue by Sev3rin** [saber-notes/saber#1177]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

If I try to enter a text in a note on the S23 using the keyboard, this is not possible because the entire screen is filled with the text attribute window and the keyboard.
See screenshot

![threema-20240317-150109551](https://github.com/saber-notes/saber/assets/47713146/f19601cf-cf8b-4b7d-8d04-67eeee5f95ae)

### To reproduce

Press the TT button on a cell phone within a note

### Expected behavior

The window with the selection of text attributes (bold, italics, etc.) should be collapsible and expandable.

### Saber version

0.21.2 FDroid

### Device

- Device: S23
- OS: Android 14 OneUi 6

**Comment by adil192** [comment]
Fixed with https://github.com/saber-notes/saber/commit/b4f33073214bba8596731f5d0419384356f21503
