### ISSUE TITLE
Wacom pen seems disregarded by Saber on macOS, despite functioning with other programs

### ISSUE THREAD

**Issue by yue-dongchen** [saber-notes/saber#1218]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

The pressure sensitivity did not work, and turning off "finger drawing" renders the stylus like the left mouseclick. However, pressure sensitivity works in [Rnote](https://rnote.flxzt.net/) and the browser (e.g. https://openprocessing.org/sketch/591905/). Similarly, the Flutter app [_Butterfly_](https://butterfly.linwood.dev/) also does not register different pressures. Please ask me if more information would be helpful.

### To reproduce

1. Install the Wacom driver and grant all required macOS permissions. Reboot computer.
2. Install and launch Saber. Try to use the stylus.

### Expected behavior

The stylus being treated as such, including pressure sensitivity

### Saber version

v0.20.2 App Store (20020)

### Device

* **System version:** macOS Sonoma 14.4.1 (23E224)
* **Tablet model:** Wacom Intuos BT S (CTL-4100WL)
* **Wacom driver version**: 6.4.5-3

**Comment by lmcj-xyz** [comment]
This is an issue in Linux as as well.

System info:
- Fedora 40
- GNOME in Wayland
- Saber version 0.21.4

Perhaps this is not even a bug but the intended behaviour, is it Saber mostly intended to be used on touch screen devices?
If that's the case, then I would imagine it's not at all a priority but a want.

That being said, there is no way to change the settings for a graphics tablet in the application, if the program is expected to use with a graphics tablet, one would like to have a settings menu such as the ones in [Rnote](https://rnote.flxzt.net/) or [Xournal++](https://xournalpp.github.io/). This is a desirable feature if Saber is intended to be a cross-platform note taking app.

**Comment by danielwmoore** [comment]
Ubuntu 24.04 here, my Wacom AES also ignored. Works great in every other app. 
Saber works as expected on my Android Samsung Galaxy Tab S7 tablet with s-pen.

Not utilizing the pen on my Ubuntu laptop is kind of a deal breaker for me, as we had hoped to use it for home school, where the kids are using Samsung tablets to do their work, with me checking it on my Linux Laptop. We were going to use a personal Next Cloud if we can get this to work. Has every feature needed except the pen working for the teacher (ME).

**Comment by adil192** [comment]
Please see https://github.com/saber-notes/saber/issues/671#issuecomment-1567626366
