### ISSUE TITLE
Random lines between the side of the hand and the tip of the stylus

### ISSUE THREAD

**Issue by Polux49** [saber-notes/saber#1235]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

I have a Surface Book 2 with dual boot Windows 10 / Manjaro Linux. Saber is installed on both, with flatpak on the linux side.

Using properly Saber in Manjaro Linux (with Gnome), is just impossible: when I write something, with the side of my hand resting on the page, **Saber randomly draws straight lines between the points where it detects my hand and the pointer of the stylus**. 

This problem doesn't occur with Saber on the same laptop with windows 10. There are a few undesired points appearing from time to time in the area of the hand, though. 

### To reproduce

Obvious (with this material). 

### Expected behavior

Obvious. 

### Saber version

v0.21.4 (21040)

### Device

- Device: Surface Book 2
- OS: Manjaro Gnome (dual boot with Windows 10)

**Comment by adil192** [comment]
This is occurring because your device isn't turning off touch while using a stylus. There are no plans currently to implement software-based palm rejection
