### ISSUE TITLE
Saber loses Nextcloud login again with version 0.23.0

### ISSUE THREAD

**Issue by Obi-Wahn** [saber-notes/saber#1252]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

Until version 0.22.0 I had the problem that I was always logged out of my Nextcloud under Windows. With version 0.22.0, I no longer had this problem on my laptop and desktop. Now the problem reappears with version 0.23.0. On the desktop the login always remains, on the laptop the login is lost every time. 
Unfortunately, I can't test whether it works again with version 0.22.0 because I can no longer find the old Windows installation files.

### To reproduce

1. log in to the private Nextcloud
2. restart the app
3. check login

### Expected behavior

Login remains active

### Saber version

v0.23.0

### Device

Laptop: Surface 8 Pro Windows 11 / Desktop: normal pc with Win 11 Pro
Nextcloud 28.0.5

**Comment by adil192** [comment]
This is a bug with https://pub.dev/packages/flutter_secure_storage or its dependencies, please file an issue there if you can make a reproducible example

**Comment by pisceswb** [comment]
+1

**Comment by Obi-Wahn** [comment]
I just tried version 1.28.2 again and connected to my Nextcloud. And then came the pleasant surprise! The connection remains intact after restarting Saber! Finally! :-)
