### ISSUE TITLE
Add brush patterns and custom pressure curves

### ISSUE THREAD

**Issue by NyxWinter** [saber-notes/saber#1278]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Motivation

I notice that whenever I write in Krita (usually with the Ink pen or Ink-4 pen), I like the way it looks a lot more than it does in Saber. I just love the look of letters with ink blobs at the start, wispy tails and gritty textures.

### Solution

Adding texture to the lines and customizable pressure curves. 

### Saber version

v0.21.4 F-Droid (21040)

### Device

- Device: Samsung Galaxy Tab S8
- OS: Android 14 (OneUI)

**Comment by NyxWinter** [comment]
Oops! I didn't realise I wasn't on the latest version and that a patterned brush has already been implemented. My bad, sorry!

Very cool, though!

**Comment by GSTbyMM** [comment]
> Oops! I didn't realise I wasn't on the latest version and that a patterned brush has already been implemented. My bad, sorry!
> 
> Very cool, though!

You can close this now.
