### ISSUE TITLE
Pen Buttons doesn't work on Redmi Pad 6 pro

### ISSUE THREAD

**Issue by Stonedpig** [saber-notes/saber#1279]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

Hello folks!
Recently my friend discovered a problem with saber on his device. The Problem is that he cannot use his pen buttons in saber. In the in-build Xiaomi note-taking APP it works.

### To reproduce

1.Go into Saber with a Xiaomi device
2.Create a note
3. Press the buttons
4. No response to the action

### Expected behavior

One button should erase the writings and the other should activate the select tool.

### Saber version

version 0.23 Fdroid

### Device

- Device: Xiaomi Redmi Pad 6 Pro
- OS: Android 14

**Comment by Iey4iej3** [comment]
https://github.com/saber-notes/saber/issues/797
https://github.com/saber-notes/saber/issues/859
