### ISSUE TITLE
Static noise playing 

### ISSUE THREAD

**Issue by exalented** [saber-notes/saber#1281]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

When the app is not being used (backgrounded) static noise plays through speakers.

### To reproduce

1. Open the app
2. Create a new note
3. Draw
4. Background the app
5. Wait (in my case ~3hrs
6. Static noise plays through the android media player

### Expected behavior

Peace

### Saber version

version 0.23.1  com.adilhanney.saber versionCode 230102

### Device

- Device: Pixel 7
- OS: GrapheneOS 14 latest

**Comment by QubaB** [comment]
Try to switch off "Pencil sound effect" in settings.

**Comment by veudal** [comment]
Your fix works @QubaB , but will there be a fix for it soon, so that I can enable the pencil sound without having it constantly in the background after one use.
