### ISSUE TITLE
Add document buttons menu popup in RTL

### ISSUE THREAD

**Issue by alr86** [saber-notes/saber#1282]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

In Right-To-Left languages, Add new document buttons not visible
![Screenshot_۲۰۲۴۰۶۰۵-۱۶۲۷۳۲_Saber](https://github.com/saber-notes/saber/assets/65030817/352d0e6a-afb1-44da-b5c2-9b263d59a02e)

### Saber version

v0.23.1

### Device

- Device: Redmi note 9
- OS: Android 14
- Language: Persian

**Comment by ZebraVogel94349** [comment]
This issue gets fixed in #1286.
