### ISSUE TITLE
Allow putting the "Slash" character in the note name

### ISSUE THREAD

**Issue by GuiSousa135** [saber-notes/saber#1291]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Motivation

I'm a student of legislation and programming, I need to use some special characters in the name of the note, and the character I need most is "/", but the app doest allow it.

### Solution

When I add the character "/", it appears: "Note name can't contain a slash". Allow the use of the "Slash" character in the note name.

### Saber version

v0.23.1 F-Droid

### Device

- Device: all
- OS: all

**Comment by nikkivirtuoso** [comment]
can you help me in resolving this issue:
Cannot create a iOS App Development provisioning profile for "com.adilhanney.saber".
Personal development teams, including "Nishant Kumar", do not support the Associated Domains capability.
