### ISSUE TITLE
iPad Pro更新后键盘乱跳，完全无法使用

### ISSUE THREAD

**Issue by wood6s** [saber-notes/saber#1295]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

iPad Pro2021 M1，saber版本0.23.3，更新后打开笔记就会跳出键盘，并且关不掉，严重影响使用，希望尽快修复

### To reproduce

打开任何笔记，翻页即可看到键盘跳出

### Expected behavior

希望能改成手动开关键盘

### Saber version

v0.23.3

### Device

- Device: iPad Pro 2021
- OS: 17.5.1

**Comment by Iey4iej3** [comment]
Same as https://github.com/saber-notes/saber/issues/1296

Since that one is in English (thus comprehensible by developers), please close this issue as a duplicate.
