### ISSUE TITLE
Regression since 0.23.3: glitching keyboard keeps toggling infinitely

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [saber-notes/saber#1296]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

On my tablet since the last update saber is almost unusable because the keyboard keeps glitching : it opens on its own, and if I press the back button it toggles on again immediately. It seems to pop up usually when zooming out. When I press back repeatedly to exit the page and go back in : the keyboard is still raised.

### To reproduce

1. Usually I zoom out while panning with my fingers
2. Notice the keyboard raises on its own
3. From that point on I quand lower the keyboard

### Expected behavior

The keyboard should not raise on its own.

### Saber version

0.23.3 from github releasss

### Device

- Device: SM-T580
- OS: android 12 on lineageos

### Anything else?

I'm so sorry my explanation are not more detailed but this bug is too random and makes the app so unusable that I'll have to downgrade.

Update: ~~it seems that the keyboard can be lowered down for good if I stay in vertical mode. I was indeed using my tablet mainly in landscape mode.~~ nevermind, its still here.

Also note that the vertical cursor bar indicating a text field is indeed visible in the top left corner. For no reason. And it keeps blinking even when the keyboard is down

**Comment by JohnmarkBeaty** [comment]
Same issue here. It keeps opening text mode and I'm unable to exit. It's frequently attempting universal clipboard and I'm unable to get it to stop. It's unusable for me as well.

I tried building and loading `0.23.2` but I just get a blank white screen.

If you have any suggestions please let me know! 🙏

**Comment by davidbartonau** [comment]
This also effects me.  App is almost unusable.  

It seems to open a text input field at the top left of a page when scrolling and in some cases it just goes in and out of text mode in an infinite loop until I trick it into stopping.

**Comment by JohnmarkBeaty** [comment]
@davidbartonau 
> until I trick it into stopping.

Have you found a consistent way to trick it? I struggle to find repeatable steps that let me take notes.

**Comment by davidbartonau** [comment]
@JohnmarkBeaty sorry, no.  The trick is just to stop the keyboard from popping up and down, otherwise it will go on forever.  

I find that once I stop it, if I don't move between pages it *tends* to work but going from page to page is an exercise in frustration.

**Comment by thiswillbeyourgithub** [comment]
Update : to me it seems triggered by the page transition. If i move far away so that the transition or top right corner is not visible, the keyboard seems to stay down

**Comment by Crowerade** [comment]
Same issue here, the keyboard opens whenever I enter a note and when I scroll down. I noticed that although the keyboard is there and does type in the note, the tool is not selected

**Comment by thiswillbeyourgithub** [comment]
To me this is fixed in 0.24.0
