### ISSUE TITLE
Detect painting board on linux

### ISSUE THREAD

**Issue by cd-FileX** [saber-notes/saber#1302]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Motivation

When I try to paint with my Huion painting pad (or whatever you call it), it is detected as finger input rather than painting input.
If enforcing the mode, the pressure level is ignored though.

### Solution

The app detecting the input from the pad automatically and inputting it with the correct pressure
OR automatically setting the painting mode instead of swipe mode

### Saber version

0.24.1

### Device

- Device: Thinkpad T530 / Huion H1060P
- OS: Kubuntu 24.10

**Comment by adil192** [comment]
See https://github.com/saber-notes/saber/issues/671#issuecomment-1567626366
