### ISSUE TITLE
Browser does not open when trying to connect to Nextcloud

### ISSUE THREAD

**Issue by Iaphetes** [saber-notes/saber#1313]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

Hi,

I'm using the Flatpak app on the Desktop and want to sync with my own Nextcloud. However when I try to connect the browser does not open.
My default browser (according to xdg-mime query default x-scheme-handler/https) is firefox.
It works on the Android app.

Thanks in advance.

### To reproduce

1. Install the Flatpak version of Saber
2. Enter a (valid) Nextcloud URL under "Other Nextcloud server"
3. Press "Login with Nextcloud"

### Expected behavior

A browser tab opening, prompting me to login and grant acces

### Saber version

com.adilhanney.saber 0.24.1 

### Device

- Device: Desktop
- OS: Arch Linux (btw ;)

### Anything else?

I tried it on an old install of Arch, where it didn't work but this is now a completely new install.

**Comment by DDzwiedziu** [comment]
I have this exact issue on Android with my local server. On one device it worked, but when I've logged out to change my encryption password it stopped working. On the other device it tried to connect once and then even stopped trying making network connections.

**Comment by DDzwiedziu** [comment]
Still occurs in v0.25.0.
