### ISSUE TITLE
Login to local Nextcloud instance with ipv4 address does not work

### ISSUE THREAD

**Issue by VibrantTreeStump** [saber-notes/saber#1318]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

I have a local Nextcloud instance that I want to use for synchronization. When trying to access it via its ipv4 address, the browser does not work. It still shows the banner "please follow the instructions in the browser" but clicking on "browser didn't open? click here" does not do anything. ~~The same thing happens when I try to access it via `hostname.local`~~
I currently have another test instance running behind a reverse proxy, and accessing it via the domain name does work. Also I can ping my "production server" via its ipv4 address, so the problem has to be in how the app handles (local) ipv4 addresses ~~and the `.local` TLD~~

### To reproduce

1. Try to access local Nextcloud instance via ipv4 ~~or `.local` address~~
2. Nothing happens

### Expected behavior

Accessing a local instance should work even without a reverse proxy

### Saber version

v0.24.2 F-Droid (24020)

### Device

- Device: Samsung Galaxy Tab S9 FE+
- OS: Android 14 (OneUI 6.1)

**Comment by QubaB** [comment]
I think nobody will take care about this problem. I think it is not saber problem.

Does it work when you use you browser (outside of saber)? How is managed nextcloud server certificate, is it issued for hostname.local?

**Comment by VibrantTreeStump** [comment]
I must have been super tired when I wrote the issue. I had only tested `ping 192.168.x.x` but I actually hadn't tested `ping hostname.local`, I have no idea why I thought I had. Now that you've said it and I actually tested it, of course `hostname.local` doesn't resolve, so that's a problem on my end. I updated the issue accordingly.

I did however test logging into Nextcloud via ipv4 again.
Some apps open the browser like saber does, some handle the login internally
- Browser:
    - Using [DAVx5](https://github.com/bitfireAT/davx5-ose), login with ipv4 works flawlessly. The browser opens and I can input the login credentials.
    - With the [Nextcloud official Android app](https://github.com/nextcloud/android) it works flawlessly as well
- Internally:
    - [Tasks.org](https://github.com/tasks/tasks) (via its CalDAV login method) works
    - [Nextcloud Cookbook](https://github.com/Teifun2/nextcloud-cookbook-flutter) works

So I'm certain the problem with ipv4 login has to be specific to saber.

**Comment by adil192** [comment]
You might need to enable self-signed certificates at the bottom of Saber's settings page

> It still shows the banner "please follow the instructions in the browser" but clicking on "browser didn't open? click here" does not do anything.

Can you share the logs?

**Comment by VibrantTreeStump** [comment]
Well, that is embarrassing... I didn't check that option. With this enabled the login works. I'm really sorry for wasting your time!
