### ISSUE TITLE
[RE-OPENED: #1304] Unable to sync with saber cloud

### ISSUE THREAD

**Issue by TekkertheChaot** [saber-notes/saber#1326]
This issue is supposed to be a reopening of #1304. 
If #1304 is to be reopened, this issue may be closed.

_(I know this is dirty and not the intended way of handling / against the CoC, but the original issue has been closed, although it still persists. No follow up has been given yet.)_

**Comment by Iey4iej3** [comment]
This is now tracked in #1320

**Comment by TekkertheChaot** [comment]
Aright, thank you for the info!
