### ISSUE TITLE
Folder permissions to 777 in MacOs from AppStore

### ISSUE THREAD

**Issue by danifgxcom** [saber-notes/saber#1376]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

When installing the app from the Apple Store, the application directories are owned by root, and the permissions are set to 777 (rwx everyone).
That is a security issue.

### To reproduce

1. With a regular user, install from the App store.
2. No need to elevate privileges like sudo.
3. The app is installed owned by root and directories (most of them) are 777 (rwx).

### Expected behavior

The app must be owned by the user and 777 permissions should never be given.

### Saber version

Last and previous 

### Device

- Device: Mac
- OS: v15

**Comment by adil192** [comment]
Thanks
