### ISSUE TITLE
Changing the saber directory to my SD card prevents me from saving notes

### ISSUE THREAD

**Issue by huste** [saber-notes/saber#1379]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

I just **freshly** installed Saber 0.25.1 from Google Play on my Galaxy Note 8. 

I failed to connect with my nextcloud instance (authentication works, I can see Saber in the list of authenticated devices, but Saber still thinks, it is not connected). So I decided to change the storage directory to one that syncs with my nextcloud periodically. It is on my SD card. And now I can't save notes at all.

### To reproduce

1. change the storage directory to one on the SD card
2. Grant permission to Saber to read/write to external storage 
3. select a directory on the SD card
4. create a new note, draw something and save it

Result: the "save" icon does not disappear and when pressing the back-button, all I get is the popup message that I can safely leave the editor after saving is complete. But nothing happens. And the selected storage directory remains empty.

### Expected behavior

Same as with the preset storage directory: save icon disappears in favour of the back arrow and I can get back out.

### Saber version

0.25.1

### Device

- Device: Samsung Galaxy Note 8
- OS: Android 9

**Comment by Edgiest05** [comment]
Changing saving directory not working is a known issue, see #1223.
You might want to leave a 👍 in the original post to raise its priority.

**Comment by huste** [comment]
I am sorry, I only searched for SD card, not custom directory. I just left a thumbs up for #1223.
I'll close this one myself
