### ISSUE TITLE
Regression 0.25.2: Selection does not move object

### ISSUE THREAD

**Issue by Luciogi** [saber-notes/saber#1401]
### Before submitting an issue, please check the following

- [X] I have searched for similar issues (both open and closed) and cannot find a duplicate
- [X] I agree to follow the [Code of Conduct](https://github.com/saber-notes/saber/blob/main/CODE_OF_CONDUCT.md)

### Describe the bug

Selection tool, does not move objects on screen

### To reproduce

1. Draw some line
2. Choose select tool
3. move drawn object

### Expected behavior

Not moving

### Saber version

0.25.2 (FOSS)

### Device

- Device: Redmi 9t
- OS: Android 14 (Lineage Os)

### Anything else?

https://github.com/user-attachments/assets/58a7f60b-79fe-4f46-b65b-c2fb797396cd

**Comment by ZebraVogel94349** [comment]
This is a duplicate of #1394.

**Comment by Luciogi** [comment]
> This is a duplicate of #1394.

ok ty
