### ISSUE TITLE
Green outline

### ISSUE THREAD

**Issue by yephny** [saber-notes/saber#184]
**Describe the bug**
A green outline appears when I touch the screen with an S-Pen. It could be by the same token [as the outline issue](https://github.com/MOIMOB/drinkable/issues/119) I have with [Drinkable](https://www.f-droid.org/packages/com.moimob.drinkable/).

**To Reproduce**
1. Open Saber. There's no need to open a note, it occurs even in the dashboard.
2. Tap the screen with an S-Pen.
3. See the outline. It's easier to see with the dark theme.

**Expected behavior**
No outline, like other apps.

**Screenshots**
<img src="https://a.pomf.cat/tfexpv.png" alt="Green outline" width=300 height=514>

**Device (please complete the following information):**
 - OS: Android 10, LineageOS

**Comment by adil192** [comment]
Just some follow up questions:
- Is this in the browser or app?
- Which version of Saber is this?

**Comment by yephny** [comment]
It's Saber v.0.5.0 downloaded from F-Droid.

**Comment by Luciogi** [comment]
I guess that is page separator

**Comment by Luciogi** [comment]
Try with new user.
- Open Settings
- Type in search bar `Users`
- Enable multiple users
- Create New one
- Install Saber there and check green outline around app

**Comment by yephny** [comment]
@Luciogi It's pretty difficult to delete the user profile in my past experience with it. I'd rather keep `multiple users` disabled.

**Comment by Luciogi** [comment]
Try this app to create virtual space https://github.com/WaxMoon/MultiApp

**Comment by yephny** [comment]
@Luciogi I have the same issue in Multi App.

**Comment by Luciogi** [comment]
@yephny Does this green outline appear when you don't use s-pen?

**Comment by yephny** [comment]
@Luciogi No, it appears only after I use the S-Pen. Galaxy Note 5.

**Comment by Luciogi** [comment]
I guess Android make Widget visible where digital stylus is detected
