### ISSUE TITLE
Open .sbn files

### ISSUE THREAD

**Issue by FBarrca** [saber-notes/saber#196]
**Is your feature request related to a problem? Please describe.**
Cant open .sbn fles
**Describe the solution you'd like**
Click on a .sbn file in the file explorer to open the file.

**Device (please complete the following information):**

 - OS: Android 13 and Windows 11
 - Version: [e.g. v0.5.2.0]

**Additional context**
On Windows, clicking a file opens the app, but it doesnt open the note.
On Android, the app doesnt appear as an option to open the file with. 
I've been looking a bit into the Android side and this might be the solution to enable open with.
https://pub.dev/packages/receive_sharing_intent

Hope it helps!

**Comment by adil192** [comment]
I've been looking for a flutter package to do that, thanks!
I'll probably go with a similar package https://pub.dev/packages/flutter_sharing_intent as it has better cross-platform support.

Linking discussion https://github.com/adil192/saber/discussions/163

**Comment by FranciscoBarCa** [comment]
A 4 day old package. How lucky! 
Although I think it is misslabeled in the site, that package only supports IOS atm.

**Comment by adil192** [comment]
> Although I think it is misslabeled in the site, that package only supports IOS atm.

How do you know?

**Comment by adil192** [comment]
> Although I think it is misslabeled in the site, that package only supports IOS atm.

Looks like it supports Android and iOS but nothing else yet: https://github.com/bhagat-techind/flutter_sharing_intent/issues/1#issuecomment-1361227715

**Comment by adil192** [comment]
[flutter_sharing_intent](https://pub.dev/packages/flutter_sharing_intent) doesn't support opening json files (yet) so I'm switching to [receive_sharing_intent](https://pub.dev/packages/receive_sharing_intent). I'll need to change this in the future as [receive_sharing_intent](https://pub.dev/packages/receive_sharing_intent) is unmaintained and only supports Android and iOS.

**Comment by adil192** [comment]
This likely only works for Android so I'll leave this issue open. We're waiting on [flutter_sharing_intent](https://pub.dev/packages/flutter_sharing_intent) to be further developed

**Comment by adil192** [comment]
> @adil192 Hi, I am using AOSP , its file manager does not seems to open in saber. I tried share option Saber is not appearing in list. Could you elaborate How to import file in saber? 

Saber should come up in the share menu. Which Android version and Saber version are you on?

**Comment by Luciogi** [comment]
@adil192 I am using Android 13 and Saber 0.5.3

**Comment by adil192** [comment]
> @adil192 I am using Android 13 and Saber 0.5.3

Please can you try [Build #114](https://github.com/adil192/saber/actions/runs/3854953617)? You should be able to open `.sbn` files in Saber regularly now

**Comment by Luciogi** [comment]
@adil192  working.

**Comment by Luciogi** [comment]
I would like to see directly editing on  .sbn which is openned through file manager. At the time 0.5.4 file is imported to data directory of application , then opened.

**Comment by Luciogi** [comment]
@adil192 Android default file manager does not list "Saber" when opening `.sbn` file. While Other file manager e.g Material Files can open `.sbn` file

**Comment by adil192** [comment]
> @adil192 Android default file manager does not list "Saber" when opening `.sbn` file. While Other file manager e.g Material Files can open `.sbn` file

In the screen recording, your `.sbn` file shows as 0 bytes. Did you manually create this file or did you export it from Saber? My guess would be that an empty file (0 bytes) would not be recognised as json, and therefore can't be opened in Saber.

**Comment by adil192** [comment]
> @adil192 Android default file manager does not list "Saber" when opening `.sbn` file. 

What does this file manager identify the file type as? Solid Explorer, for example, sees it as `application/*`.

**Comment by Luciogi** [comment]
![image](https://user-images.githubusercontent.com/84625092/212561578-ab903d4d-7eef-4c1a-a3d3-43315f939b37.png)

**Comment by adil192** [comment]
> @adil192 Android default file manager does not list "Saber" when opening `.sbn` file.

No promises but please can you try [Build #146](https://github.com/adil192/saber/actions/runs/3926403425)?

**Comment by Luciogi** [comment]
@adil192 not working

**Comment by Luciogi** [comment]
@adil192 I noticed, when renaming `.sbn` to `.json` extension , then opening that `.json` show saber in app list

**Comment by strk** [comment]
I cannot open .sbe files either, would that be better raised as a different issue or is it the same?

**Comment by AdmerStroh** [comment]
Would it be possible to add an import button for sbn files (opening the file picker), that just moves the selected sbn file (from a previous export) to the saber documents folder?
