### ISSUE TITLE
Allow Android users to sync to a local folder

### ISSUE THREAD

**Issue by yephny** [saber-notes/saber#24]
Would you consider adding Syncthing support? Nextcloud is too heavy-weight for my home use case, where Syncthing suffices with its P2P support that doesn't require internet connection. It should be fairly easy to implement. [Joplin](https://github.com/laurent22/joplin-android) does this by synchronizing notes to/from a directory in the system.

**Comment by adil192** [comment]
I assume you're on Android?

**Comment by yephny** [comment]
That's right.

**Comment by mtoniott** [comment]
Is it still planned ? Ty for your work by the way !

**Comment by TheModernWizard** [comment]
Yes, this would be amazing! Thanks for this great app!

**Comment by Iey4iej3** [comment]
Maybe it would be better to set up a local folder for Saber instead of sync with a local folder, with the possibility to transfer current files into the newly chosen folder.

**Comment by ColoursofOSINT** [comment]
Syncthing support with this feature would be great!

**Comment by TheModernWizard** [comment]
Somehow my previous comment here was marked as spam, but I agree with this request; Syncthing support would be amazing!

**Comment by adil192** [comment]
> my previous comment here was marked as spam

Please refrain from "I want this too" comments. Simply add a thumbs up to the issue

**Comment by TheModernWizard** [comment]
Alright, thanks for the heads-up. 

Also, is this a feature that is planned? Thanks for your work on this project!

**Comment by adil192** [comment]
This is planned but not high priority

**Comment by Iey4iej3** [comment]
> This is planned but not high priority

It seems reasonable to increase the priority of this a bit: I have just suffered from a data loss probably due to a sync bug. It seems difficult right now to do proper versioning: there are ancient versions on Nextcloud servers, but the file names are hashed (and maybe encrypted), which makes it difficult to recover from a data loss.

**Comment by sai-foss** [comment]
saving to local storage also allows users to use sync applications like syncthing to backup and version control notes. I am not sure how this would work on iOS...

**Comment by sai-foss** [comment]
@KB1RD  I am trying to get this to work with root. and syncthing as superuser. The `/data/data/com.adilhanney.saber/ `directory does not exist? has the directory changed?

**Comment by sai-foss** [comment]
update i can see the directory using a file manager. Looks like its a syncthing issue

**Comment by itsaj26744** [comment]
What is state of this feature now?

**Comment by nmbvd** [comment]
i very need this feature , hope to add to saber soon. thanks authors advance!!   i will use saber on windows only ,
