### ISSUE TITLE
windows: release a portable zip

### ISSUE THREAD

**Issue by xmha97** [saber-notes/saber#345]
Hi,
Please add zipped app to release page.
I don't want to install this app.
Thanks.

**Comment by adil192** [comment]
Hi, may I ask why you don't want to install Saber?

**Comment by xmha97** [comment]
> Hi, may I ask why you don't want to install Saber?

I prefer portable apps because I can use them without installation and even run them from a flash drive.

**Comment by HWiwoiiii** [comment]
@adil192 May I ask for the Windows portable release again now that a year has passed? Could you please consider this request again?
Thank you ~
