### ISSUE TITLE
Upload everything when logging in to a new account

### ISSUE THREAD

**Issue by Iey4iej3** [saber-notes/saber#781]
### Motivation

When login to a sync account (say, a new account), but now there are already several notes, I want to force upload everything to the account.

### Solution

Have a button to force sync everything.

### Alternatives

Current workaround: edit every note to force sync; this is very cumbersome.

### Saber version

v0.14.2 (F-Droid)

### Device

- Device:
- OS:

**Comment by ceskyDJ** [comment]
I think adding a new button could be a little confusing for most users (who don't need this at all). What about to force sync, when you hold the sync button (with a proper information in settings, with a way to out-out it)?

**Comment by Iey4iej3** [comment]
https://github.com/saber-notes/saber/commit/41088e47559a83d31b23983870a27da2f9a37f22
