### ISSUE TITLE
Pen buttons on Android

### ISSUE THREAD

**Issue by xx1182** [saber-notes/saber#859]
### Describe the bug

A button on the pen, it's usually for erasing, or whatever you set it.

### To reproduce

1. Open the app
2. Start a new note or whiteboard
3. Draw
4. Press the button on the pen

### Expected behavior

When you press the button, it should select the eraser or hilghliter tool; relase the button, and 6oure back to pen input.

### Saber version

v0.14.11 Google Play (14110)

### Device

- Device: Samsung Galaxy Fold 4
- OS: Android 13

### Anything else?

Great app, but please record yourself drawing with a pencil on paper and add it as an additional option to hear the brushing. Otherwise, responsive, still great!

**Comment by Iey4iej3** [comment]
SPen button should work to some extent, and now it is working as an eraser, although there are some minor issues: https://github.com/adil192/saber/issues/797#issuecomment-1636720025

**Comment by xx1182** [comment]
> SPen button should work to some extent, and now it is working as an eraser, although there are some minor issues: [#797 (comment)](https://github.com/adil192/saber/issues/797#issuecomment-1636720025)

Mine doesn't, probably because isn't the "powered one"(the pro version which uses Bluetooth or the ones inside the Note series), it's the fold one.
It works to some extent like you said, it gets recognised as a pen so don't have to use the "draw with finger", but the physical button doesn't work, nothing happens

**Comment by ceskyDJ** [comment]
Did you try to touch the screen by the pen, and while holding the pen on the screen tap the button on the pen? It's not good UX, but it should work (toggle eraser). Saber waits for better pen support by Flutter. For now, we need to wait, too, and hope the stylus support will come early.

**Comment by xx1182** [comment]
No, did not try it and infact works as you say.

Is there any plan to support "pixel eraser", erases around a radius?
Regards.

**Comment by srghma** [comment]
> Did you try to touch the screen by the pen, and while holding the pen on the screen tap the button on the pen

Works

**Comment by adil192** [comment]
> Is there any plan to support "pixel eraser", erases around a radius? Regards.

It's not currently a high priority issue, see https://github.com/adil192/saber/issues/40.

**Comment by djibux** [comment]
Same issue as OP, with a Samsung Galaxy S6 lite.  Pen is also not powered.

> Did you try to touch the screen by the pen, and while holding the pen on the screen tap the button on the pen
Indeed that works: the pen needs to be touching the screen.  Hovering is not enough.

**Comment by Iey4iej3** [comment]
> Indeed that works: the pen needs to be touching the screen. Hovering is not enough.

This is a (very old) bug of flutter: https://github.com/flutter/flutter/issues/42846

I guess that it might help if you react there.

**Comment by shayan15sa** [comment]
Hey guys wanted let you know erasing with spen button works on Android 14
I just uptaded my tab s6 lite to android 14 now.It didn't used to work when I was on Android 13 but now it works fine.

**Comment by Microwave-WYB** [comment]
> Hey guys wanted let you know erasing with spen button works on Android 14 I just uptaded my tab s6 lite to android 14 now.It didn't used to work when I was on Android 13 but now it works fine.

How did you managed to update Tab S6 Lite to Android 14? I don't even receive Android 14 update on my S7+

**Comment by shayan15sa** [comment]
> > Hey guys wanted let you know erasing with spen button works on Android 14 I just uptaded my tab s6 lite to android 14 now.It didn't used to work when I was on Android 13 but now it works fine.
> 
> How did you managed to update Tab S6 Lite to Android 14? I don't even receive Android 14 update on my S7+

Hi
I have the newer model (tab s6 lite 2022). I think that's why. There are some unofficial ram too.

**Comment by Robin-Sch** [comment]
For me, whenever I press the button and then touch a non-drawn part of the screen, it will undo the last action. So, whenever I want to erase something I need to be very precise or else it'll undo the last thing instead of erasing. Is it possible to disable this?
As a workaround, I figured out that when hovering above the screen, pressing and releasing button and then touching the screen will always erase and not undo, but this is quite inconvenient and requires precise timings. I do not care about the undo feature and whenever I press the button I just want to erase, is it possible to change this, somehow?
