### ISSUE TITLE
Play a pencil sound while writing

### ISSUE THREAD

**Issue by adil192** [saber-notes/saber#877]
### Motivation

Requested by @xx1182 in https://github.com/adil192/saber/issues/859:
> Great app, but please record yourself drawing with a pencil on paper and add it as an additional option to hear the brushing. Otherwise, responsive, still great!

### Saber version

v0.14.11 (14111)

### Device

Unknown

**Comment by GuiSousa135** [comment]
Very good, even it would be cool to have sounds for the marker and for the eraser, provided that you have in the settings the option of "disable sounds"
