### ISSUE TITLE
Latest version 0.17.0 is not in F-Droid

### ISSUE THREAD

**Issue by EbnedI** [saber-notes/saber#973]
### Describe the bug

The latest version of Saber isn't available in F-Droid so there is no way to update the app for people who installed Saber from F-Droid instead of PlayStore.

### To reproduce

Go to https://f-droid.org/en/packages/com.adilhanney.saber/

### Expected behavior

Be able to update to 0.17.0 version

### Saber version

v0.16.1 F-Droid(16010)

### Device

- Device: Samsung Galaxy Tab S6 Lite
- OS: Android 13

**Comment by adil192** [comment]
F-Droid updates are a bit slower because of the review process which I have no control over. That being said, it should be on now.

**Comment by EbnedI** [comment]
I didn't know, thanks.
