### ISSUE TITLE
Differentiate between finger and pen

### ISSUE THREAD

**Issue by austinliuigi** [saber-notes/saber#992]
### Motivation

It would be nice to be able to pan when dragging a page using your finger.

### Solution

If using your finger and your pen can be differentiated, they can have separate behavior (e.g. dragging your finger on the page will cause Saber to pan, whereas dragging your pen would use the selected tool). I only just discovered Saber, looking for a foss alternative to GoodNotes, so forgive me if this is a poor request.

Thank you for the great software :D

### Saber version

v0.17.1 App Store (17010)

### Device

- Device: iPad Pro
- OS: iPadOS 16.7.2

**Comment by adil192** [comment]
Simply turn off "finger drawing" in the toolbar

**Comment by austinliuigi** [comment]
Don’t know how I missed that. Thanks!
