### ISSUE TITLE
Unable to import to the root directory

### ISSUE THREAD

**Issue by Iey4iej3** [saber-notes/saber#996]
### Describe the bug

After importing to the root directory, the file does not show in the "browser" tab. It is shown in "recent", but it is shown in "/null", and I cannot move it to other directories.

### To reproduce

1. Go to "browser".
2. Import an SBN2 file.
3. Check in the "browser" tab: it does not show.

Additional tests:

4. Go to "recent".
5. Move the imported one into another directory.
6. Check in the "browser" tab: not in the directory thay the file is moved to.

### Expected behavior

Correctly imported.

### Saber version

v0.17.0 F-Droid (17000)

### Device

- Device: -
- OS: Android 13

**Comment by ZebraVogel94349** [comment]
This is fixed by #977

**Comment by atahanacar** [comment]
Notes imported this way "incorrectly" cant't be moved to any other directory.

**Comment by ZebraVogel94349** [comment]
> Notes imported this way "incorrectly" can't be moved to any other directory.

This is now also fixed by #977
